name: fivem_browser
description: Server browser for the cfx.re / FiveM server list.
publish_to: "none"
version: 1.8.2+11

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  shared_preferences: ^2.3.3
  flutter_local_notifications: ^18.0.1
  workmanager: ^0.9.0+3
  share_plus: ^10.1.3
  audioplayers: ^6.1.0
  quick_actions: ^1.0.0
  home_widget: ^0.7.0
  google_fonts: ^6.2.1
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true
  assets:
    - assets/icon/app_icon.png
    - assets/sounds/tap.wav
    - assets/sounds/notif_chime.wav
    - assets/sounds/notif_bell.wav

flutter_launcher_icons:
  android: true
  image_path: "assets/icon/app_icon.png"
